makevis.so: makevis.c ./Makefile
	gcc -O3 -Wall -fPIC -shared -I/home/ubuntu/anaconda/pkgs/python-2.7.10-0/include/python2.7/ /home/ubuntu/anaconda/pkgs/python-2.7.10-0/lib/libpython2.7.so \
	-o makevis.so makevis.c